title: 李飞江
url: https://feijiangli.github.io/

# Owner/author information
owner:
  avatar: lfj.jpg
  email: feijiangli@163.com
  github: https://github.com/FeijiangLi

links:
  - title: 简介
    url: /
  - title: 发表论文
    url: /publications/
  - title: 科研项目
    url: /teams/
  - title: 学术活动与荣誉
    url: /awards/
